### PR TITLE
Styled "forgot password" button

### PR DESCRIPTION
**Pull request by ChristineJ82**
1. Moved the button up a little
2. Change the color to a blue color that's within the site's theme colors
3. Added a "?" at the end.

### CODE REVIEW

**Comment by trybick** [comment]
@ChristineJ82  The color and text look perfect 👌. I think the Forgot Password feels too high up. Would you be interested in trying to put the Forgot Password inside the ModalFooter so it would be be in line with the bottom buttons?

**Comment by ChristineJ82** [comment]
@trybick sure! I''ll work on moving the "forgot password" link to inside the ModalFooter.

**Comment by ChristineJ82** [comment]
@trybick I moved the "forgot password" link below the ModalFooter. Having the link within the footer inline with the other buttons would make it look busy. It looks better on it's own line and easier for someone to click on if they need to.

**Comment by trybick** [comment]
@ChristineJ82 How about something like this - I fear having it on its own line creates too much empty white space just on that line. Here is decreasing the font size and having it on the same line?

Screen Shot 2020-10-17 at 12 23 52 PM

**Comment by ChristineJ82** [comment]
@trybick ok. I'll work on adding it inline with a smaller font size. My issue was with the second modal box when you click on "forgot password" and the blue button is a bit longer so the "Back to Sign In" text may not fit that well. But I'll play with the styling to see what I can do.

**Comment by trybick** [comment]
Gotcha that might be tricky

**Comment by ChristineJ82** [comment]
@trybick I got the "forgot password/back to login" text to be inline with the buttons. It was a little tricky. Let me know what you think.

**Comment by trybick** [comment]
@ChristineJ82 Awesome, thanks!

**Pull request merged**
