### PR TITLE
feat(eslint): enforce props alphabetical sorting

### PR DESCRIPTION
**Pull request by luisFilipePT**
Enforce props alphabetical sorting by updating eslint config

* Updated all files on `front` according to the new rules
* Defaults used for `Enforce props alphabetical sorting`

For reference can be tweaked this way:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md

cheers

### CODE REVIEW

**Comment by trybick** [comment]
@luisFilipePT Thanks for solving conflicts. Could you add the `shorthandLast` rule to the config? So that boolean/shorthand values come last after all props. Then looks good to merge.

**Comment by luisFilipePT** [comment]
> @luisFilipePT Thanks for solving conflicts. Could you add the `shorthandLast` rule to the config? So that boolean/shorthand values come last after all props. Then looks good to merge.

sure

**Comment by trybick** [comment]
@luisFilipePT Awesome 👏

**Comment by luisFilipePT** [comment]
@trybick check if this would help on the colors issue 😄 

https://codesandbox.io/s/get-unique-color-by-id-7z98w?file=/src/App.js

I can still improve it a bit.

**Comment by trybick** [comment]
@luisFilipePT Interesting, looks pretty nice.

Is it possible to remove colors that are too light? For example, if I change the color of the text to white, which I think the calendar text is in the app, some of the colors are too light (see picture below). 

Also someone opened a PR for this issue too. If you have any thoughts on it 
[https://github.com/trybick/tv-minder/pull/48](https://github.com/trybick/tv-minder/pull/48)

Screen Shot 2020-10-04 at 2 00 02 PM

**Comment by trybick** [comment]
@luisFilipePT Hey also, did you run eslint or prettier to fix the order of props? When I run either it doesn't seem to fix the files if I have one that isn't alphabetized.

**Comment by luisFilipePT** [comment]
> @luisFilipePT Hey also, did you run eslint or prettier to fix the order of props? When I run either it doesn't seem to fix the files if I have one that isn't alphabetized.

Yes, I run `npm run format` inside the `front` folder and it formatted everything, I tested it.

Also in my IDE I used both `eslint` and `prettier` and they both worked. 🤔 

If you give more details I can try to reproduce on my side

**Comment by luisFilipePT** [comment]
> @luisFilipePT Interesting, looks pretty nice.
> 
> Is it possible to remove colors that are too light? For example, if I change the color of the text to white, which I think the calendar text is in the app, some of the colors are too light (see picture below).
> 
> Also someone opened a PR for this issue too. If you have any thoughts on it
> #48
> 
> Screen Shot 2020-10-04 at 2 00 02 PM

I have updated the sandbox to try to guarantee the contrast ratio, meaning that the text color changes according to the background, for most cases seems to work imo 😄 , take a look.

**Comment by trybick** [comment]
I think the solution in the other PR works better in this case because it's less changes overall. Appreciate the work tho 🙌 
https://github.com/trybick/tv-minder/pull/48

**Pull request merged**
